### PR TITLE
adding the long standing family law policy

### PR DESCRIPTION
**Pull request by sfryer**
[LPoC Family Law Policy (Apr '97 - Apr '06)](https://web.archive.org/web/20060405113359/http://www.libertarian.ca/english/enpolicy.htm)
new file:   family_law.md

### CODE REVIEW

**Comment by zramsay** [comment]
Can you remove the refs and maybe just add the link within the file - reduces clutter.

**Comment by sfryer** [comment]
sure. the reason I did it that way was to provide a baseline to modify so that all original information is in the repo.

**Comment by zramsay** [comment]
good point. I wonder if there's a better way to parse information for (pretty) display/consumption & reference info. thoughts?

**Comment by sfryer** [comment]
perhaps the current list of .md files can serve as a summary for information in a corresponding directory or files. so for example family_law/references.md or family_law-reference.md or the like. ?

**Comment by zramsay** [comment]
yeah, a dir for each topic then; with additional files as needed within that dir?

**Comment by sfryer** [comment]
sounds good to me.

**Comment by sfryer** [comment]
do you really want that boilerplate software license in there too? wouldn't it be better to use something from https://creativecommons.org/ ?

**Comment by zramsay** [comment]
i don't know the difference between licenses well enough to have an opinion.

**Comment by zramsay** [comment]
but we want this to be a repo for the people so feel free to pull request away ... I'll probably accept most of them

**Pull request merged**
